name = "MathematicalSystems"
uuid = "d14a8603-c872-5ed3-9ece-53e0e82e39da"
version = "0.14.2"

[deps]
Espresso = "6912e4f1-e036-58b0-9138-08d1e6358ea9"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Espresso = "0.6"
InteractiveUtils = "<0.0.1, 1.6"
LazySets = "5"
LinearAlgebra = "<0.0.1, 1.6"
MacroTools = "0.5"
MultivariatePolynomials = "0.3 - 0.5"
RecipesBase = "0.6 - 0.8, 1"
Requires = "1.3.1"
SparseArrays = "<0.0.1, 1.6"
julia = "1.6"

[extensions]
LazySetsExt = "LazySets"

[extras]
LazySets = "b4f0291d-fe17-52bc-9479-3d1a343d9043"

[weakdeps]
LazySets = "b4f0291d-fe17-52bc-9479-3d1a343d9043"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
